function f() {
	throw "FEHLER";
}


function main() {
	var a = 42;
	std::println(a);
	f();
	var x = 1 + 2;
	std::println(x);
}
except(error) {
	std::println(error);
}